version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: referral_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - referral_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: referral_app
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - CACHE_ENABLED=${CACHE_ENABLED}
      - CACHE_TTL=${CACHE_TTL}
    networks:
      - referral_network

  mysql:
    image: mysql:8.0
    container_name: referral_mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - referral_network

volumes:
  mysql_data:

networks:
  referral_network:
    driver: bridge
